# version: "3.8"

# services:
#   postgres:
#     image: postgres:16
#     container_name: reviewlens_postgres
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: reviewlens
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - reviewlens
#     restart: unless-stopped

#   redis:
#     image: redis:7
#     container_name: reviewlens_redis
#     ports:
#       - "6379:6379"
#     networks:
#       - reviewlens
#     restart: unless-stopped

# networks:
#   reviewlens:
#     driver: bridge

# volumes:
#   postgres_data:


services:
  postgres:
    image: postgres:16
    # container_name: reviewlens_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-reviewlens}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    # container_name: reviewlens_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
